config/routes.rb
Rails.application.routes.draw do
 
  resources :photos do
  member do
    get 'like'
  end
end

  
  root to: 'photos#index'
  get 'static_pages/home'
  
  

end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  photo_url   :string(255)
#  date        :datetime
#  created_at  :datetime
#  updated_at  :datetime
#

class Photo < ActiveRecord::Base
  default_scope {order('likes DESC')}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def show
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.save!
    redirect_to photos_path
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
     @photo = Photo.find(params[:id])
     @photo.update_attributes(photo_params)
    redirect_to photos_path
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.delete
    redirect_to photos_path
  end
   
  def photo_params
    params.require(:photo).permit(:title, :photo_url, :description, :date)
  end
  
  def like
    @photo = Photo.find(params[:id])
    cookie_id = params[:id].to_sym
    if session[cookie_id]
      session[cookie_id] = nil
      @photo.likes = @photo.likes - 1
      flash[:error] = "You don't like it!"
    else
    session[cookie_id] = true
      @photo.likes = @photo.likes + 1
      flash[:success]= 'You like it!'
    end
         @photo.save!
      redirect_to photos_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @from_controller = "zmienna zadeklarowana"
    @linki = { 'facebook' => 'http://www.facebook.com', 'google' => 'http://google.pl' }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projekt1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= bootstrap_flash %>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
     <img src='http://railsgirls.com/images/railsgirls-sq.png' alt="photo"> </img>
      <p> Ta aplikacja powstała w trakcie warsztatów RailsGirls Poznan 2014 </p>
    </div>
  </div>
</div>


  <%= link_to "All photos", photos_path, class: 'btn btn-default' %>
  <%= link_to "Add a new photo", new_photo_path, class: 'btn btn-danger' %>
  
  <button class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">About this app</button>
  

  <%= yield %>

</body>
</html>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/edit.html.erb
<div>
  <%= form_for @photo do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :description %>:
  <%= f.text_field :description %><br />
  
   <%= f.label :photo_url %>:
  <%= f.text_field :photo_url %><br />
  
  <%= f.label :date %>:
  <%= f.text_field :date %><br />

  <%= f.submit %>
   <% end %>
  </div>

app/views/photos/index.html.erb
<h1>MY PHOTOS</h1>

<% if @photos.empty? %>
  <p> There are no photos! </p>
<% else %>

  <% @photos.each_with_index do |photo, index| %>

  <% if index % 3 == 0 %>
    <div class="row">  
   <% end %>

    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="<%= photo.photo_url %>" width='250' height=300 alt="photo" </img>
        <div class="caption">
          <h3><%= photo.title %></h3>
          <p><%= photo.description %></p>
          <p> Likes: <%= photo.likes%> </p>
          <%= link_to 'edit photo', edit_photo_path(photo), class: 'btn btn-info' %>
          <%= link_to 'delete', photo_path(photo), class: 'btn btn-danger', method: :delete, data: {confirm: "Na pewno?"} %>

          <% cookie_id = session[photo.id.to_s.to_sym] %>
          <% if cookie_id %>
          <%= link_to "I don't like it!", like_photo_path(photo), class: 'btn btn-danger' %>
          <% else %>
          <%= link_to "I like it!", like_photo_path(photo), class: 'btn btn-warning' %>
          <% end %>
          
        </div>
      </div>
    </div>

    <% if index % 3 == 2 %>
      </div>
    <% end %>

  <% end %>
<% end %>

app/views/photos/new.html.erb
<div>
  <%= form_for @photo do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :description %>:
  <%= f.text_field :description %><br />
  
   <%= f.label :photo_url %>:
  <%= f.text_field :photo_url %><br />
  
  <%= f.label :date %>:
  <%= f.text_field :date %><br />

  <%= f.submit %>
   <% end %>
  </div>

app/views/photos/show.html.erb
<h1>Photos#show</h1>
<p>Find me in app/views/photos/show.html.erb</p>

app/views/photos/update.html.erb
<h1>Photos#update</h1>
<p>Find me in app/views/photos/update.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Rails Girls start</h1>
<h2>Marta Marta</h2>
<p>taki znacznik</p>
<b>drugi taki znacznik</b>
<ul>
<li>numer 1</li>
<li>numer 2</li>
<li>numer 3</li>
</ul>
<ol>
<li>numer 1</li>
<li>numer 2</li>
<li>numer 3</li>
</ol>
<a href='http://www.facebook.com' target='_blank'> to jest link</a>
<%= Time.now %>

<% @linki.each do |name, link| %>
<br><a href='<%= link %>' target='_blank'> <%=name %></a>
 
<% end %>

<%= @from_controller %>